export interface WorkflowTemplate {
  id: string;
  name: string;
  purpose: string;
  category: "FINANCE" | "COMPLIANCE" | "OPERATIONS" | "SUPPORT" | "ZERO-KEY PUBLIC APIS" | "SECURITY & DEVOPS" | "FINANCE & INTEL" | "OPEN SOURCE & SELF-HOSTED";
  badge: string;
  stepsSummary: string[];
  instructions: string;
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  examples: Array<{ input: Record<string, unknown>; output: Record<string, unknown> }>;
  allowedTools: string[];
  actionsRequiringApproval: string[];
  maxExecutionSteps: number;
}

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "customer_refund_automation",
    name: "Customer Refund Automation",
    purpose: "Bounded multi-step workflow: retrieves customer policy, extracts refund parameters, evaluates deterministic rules, requests human approval for disbursements, and generates a final audit report.",
    category: "FINANCE",
    badge: "HITL GATED · DECISION EXPLAINER",
    stepsSummary: ["Structured Input", "Doc Retrieval", "AI Extraction", "Deterministic Condition", "Human Approval", "Mock Action", "Final Report"],
    instructions: "1. Search for customer policy. 2. Extract refund amount and invoice number. 3. Evaluate if refund amount > $500. 4. If high value, request manager approval. 5. If approved, dispatch mock refund task. 6. Generate final report.",
    inputSchema: {
      type: "object",
      properties: {
        customerName: { type: "string", description: "Name of customer requesting refund" },
        requestText: { type: "string", description: "Customer inquiry or support ticket text with amount and reason" },
      },
      required: ["customerName", "requestText"],
    },
    outputSchema: {
      type: "object",
      properties: {
        report: { type: "object" },
        status: { type: "string" },
      },
    },
    examples: [
      {
        input: {
          customerName: "Acme Logistics",
          requestText: "Customer requested a $750.00 refund due to damaged shipment on invoice #INV-8891",
        },
        output: { status: "COMPLETED" },
      },
    ],
    allowedTools: [
      "document_search",
      "ai_extraction",
      "deterministic_condition",
      "mock_task_creator",
      "final_report",
    ],
    actionsRequiringApproval: ["create_task"],
    maxExecutionSteps: 10,
  },
  {
    id: "invoice_risk_screening",
    name: "Invoice Compliance & Risk Screening",
    purpose: "Extracts vendor invoice line items, classifies transaction risk category, applies deterministic threshold tests, and synthesizes an executive compliance report.",
    category: "COMPLIANCE",
    badge: "AUTOMATED AUDIT · SAFE RETRY",
    stepsSummary: ["Structured Input", "AI Extraction", "AI Classification", "Deterministic Condition", "Final Report"],
    instructions: "1. Extract invoice amount, vendor name, and tax ID from invoice text. 2. Classify risk level (STANDARD, SUSPICIOUS, URGENT). 3. Evaluate if amount > $10,000 or risk is SUSPICIOUS. 4. Compile executive compliance report.",
    inputSchema: {
      type: "object",
      properties: {
        vendorName: { type: "string" },
        invoiceText: { type: "string" },
      },
      required: ["vendorName", "invoiceText"],
    },
    outputSchema: {
      type: "object",
      properties: {
        complianceStatus: { type: "string" },
        executiveReport: { type: "object" },
      },
    },
    examples: [
      {
        input: {
          vendorName: "Globex Corp",
          invoiceText: "Invoice #GLX-4001: Amount: $14,250.00. Expedited consulting retainer.",
        },
        output: { complianceStatus: "FLAGGED_FOR_AUDIT" },
      },
    ],
    allowedTools: [
      "ai_extraction",
      "ai_classification",
      "deterministic_condition",
      "final_report",
    ],
    actionsRequiringApproval: [],
    maxExecutionSteps: 8,
  },
  {
    id: "support_ticket_triage",
    name: "Support Ticket Intent Triage & Escalation",
    purpose: "Classifies incoming customer support tickets, searches relevant knowledge base solutions, creates high-priority escalations when necessary, and generates resolution summaries.",
    category: "SUPPORT",
    badge: "CLASSIFICATION · KNOWLEDGE SEARCH",
    stepsSummary: ["Structured Input", "AI Classification", "Doc Retrieval", "Deterministic Condition", "Mock Action", "Final Report"],
    instructions: "1. Classify ticket intent into categories (BILLING, TECHNICAL_SUPPORT, SECURITY_INCIDENT). 2. Retrieve knowledge base articles for the issue. 3. If category is SECURITY_INCIDENT, escalate task with HIGH priority. 4. Output structured response report.",
    inputSchema: {
      type: "object",
      properties: {
        ticketId: { type: "string" },
        customerEmail: { type: "string" },
        ticketBody: { type: "string" },
      },
      required: ["ticketId", "customerEmail", "ticketBody"],
    },
    outputSchema: {
      type: "object",
      properties: {
        assignedQueue: { type: "string" },
        resolutionSummary: { type: "string" },
      },
    },
    examples: [
      {
        input: {
          ticketId: "TCK-9901",
          customerEmail: "user@example.com",
          ticketBody: "I cannot access my account and received an unauthorized password reset email.",
        },
        output: { assignedQueue: "SECURITY_ESCALATION" },
      },
    ],
    allowedTools: [
      "ai_classification",
      "document_search",
      "deterministic_condition",
      "mock_task_creator",
      "final_report",
    ],
    actionsRequiringApproval: ["create_task"],
    maxExecutionSteps: 10,
  },
  {
    id: "trending_tech_hackathon_radar",
    name: "Trending Tech & Hackathon Radar",
    purpose: "Fetches live Hacker News discussions and GitHub trending repositories, runs an AI Tech Scout to synthesize emerging engineering paradigms, and produces a daily briefing.",
    category: "ZERO-KEY PUBLIC APIS",
    badge: "ZERO-KEY · HACKER NEWS & GITHUB",
    stepsSummary: ["HN Top Stories", "GitHub Trending", "Tech Scout Analysis", "Discord/Slack Dispatch"],
    instructions: "1. Fetch top hacker news stories. 2. Fetch trending repositories. 3. Synthesize tech radar briefing. 4. Dispatch alert.",
    inputSchema: { type: "object", properties: { topic: { type: "string" } } },
    outputSchema: { type: "object", properties: { briefing: { type: "string" } } },
    examples: [{ input: { topic: "AI Agents" }, output: { status: "DELIVERED" } }],
    allowedTools: ["http", "notification_dispatcher"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 6,
  },
  {
    id: "web_page_intel_summarizer",
    name: "Web Page Intel & Summarizer",
    purpose: "Extracts markdown from any live website URL using Jina Reader (r.jina.ai) and structures an intelligence dossier.",
    category: "ZERO-KEY PUBLIC APIS",
    badge: "ZERO-KEY · JINA READER",
    stepsSummary: ["Jina Web Reader", "Data Mapping", "Intel Agent Analysis", "Dossier Output"],
    instructions: "1. Convert target URL into clean markdown via Jina Reader. 2. Map core article metadata. 3. Synthesize executive intel dossier.",
    inputSchema: { type: "object", properties: { targetUrl: { type: "string" } }, required: ["targetUrl"] },
    outputSchema: { type: "object", properties: { dossier: { type: "string" } } },
    examples: [{ input: { targetUrl: "https://openai.com/index/hello-gpt-4o/" }, output: { status: "COMPLETED" } }],
    allowedTools: ["web_reader", "data_mapper"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 5,
  },
  {
    id: "arxiv_ai_research_paper_scout",
    name: "ArXiv AI Research Paper Scout",
    purpose: "Scans recent research papers in cs.AI / cs.CL from ArXiv's public API, evaluates model architecture breakthroughs, and produces a structured research memo.",
    category: "ZERO-KEY PUBLIC APIS",
    badge: "ZERO-KEY · ARXIV PUBLIC API",
    stepsSummary: ["ArXiv Feed Ingestion", "AI Research Scientist", "Research Memo Output"],
    instructions: "1. Ingest ArXiv AI RSS/Atom feed. 2. Filter for reasoning/RL breakthroughs. 3. Format structured research brief.",
    inputSchema: { type: "object", properties: { category: { type: "string" } } },
    outputSchema: { type: "object", properties: { researchMemo: { type: "string" } } },
    examples: [{ input: { category: "cs.AI" }, output: { status: "COMPLETED" } }],
    allowedTools: ["rss_feed"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 5,
  },
  {
    id: "extreme_weather_disaster_alert",
    name: "Extreme Weather & Disaster Alert",
    purpose: "Monitors live seismic data from USGS and weather forecasts from Open-Meteo without authentication; triggers emergency response advisory when thresholds are exceeded.",
    category: "ZERO-KEY PUBLIC APIS",
    badge: "ZERO-KEY · OPEN-METEO & USGS",
    stepsSummary: ["Open-Meteo Forecast", "USGS Seismic Stream", "Risk Evaluation Router", "Emergency Broadcast"],
    instructions: "1. Fetch Open-Meteo conditions. 2. Fetch USGS seismic events. 3. If risk threshold exceeded, formulate civil safety bulletin.",
    inputSchema: { type: "object", properties: { latitude: { type: "number" }, longitude: { type: "number" } } },
    outputSchema: { type: "object", properties: { safetyBulletin: { type: "string" } } },
    examples: [{ input: { latitude: 37.77, longitude: -122.42 }, output: { status: "RESOLVED" } }],
    allowedTools: ["http", "notification_dispatcher"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 6,
  },
  {
    id: "zero_day_cve_watcher",
    name: "Zero-Day & CVE Vulnerability Watcher",
    purpose: "Monitors newly published CVE vulnerabilities via CIRCL/OSV.dev, filters high severity (CVSS > 7.0), triggers a SecOps Impact Agent, and requires human approval before dispatching incident alerts.",
    category: "SECURITY & DEVOPS",
    badge: "DEVSEC · CIRCL CVE & HITL GATE",
    stepsSummary: ["Fetch CIRCL CVEs", "CVSS Filter", "SecOps Impact Agent", "Security Lead Approval", "Slack Alert Dispatch"],
    instructions: "1. Query latest CVE entries. 2. Filter high severity CVSS. 3. SecOps agent generates mitigation plan. 4. Human sign-off. 5. Dispatch incident alert.",
    inputSchema: { type: "object", properties: { minCvss: { type: "number" } } },
    outputSchema: { type: "object", properties: { incidentReport: { type: "string" } } },
    examples: [{ input: { minCvss: 7.0 }, output: { status: "APPROVED_AND_DISPATCHED" } }],
    allowedTools: ["http", "notification_dispatcher"],
    actionsRequiringApproval: ["dispatch_security_alert"],
    maxExecutionSteps: 7,
  },
  {
    id: "crypto_momentum_arbitrage_pulse",
    name: "Crypto Momentum & Arbitrage Pulse",
    purpose: "Fetches real-time price changes from CoinGecko and Binance public ticker endpoints, routes on high volatility (> 5% 24h delta), and triggers an AI Quant Analyst.",
    category: "FINANCE & INTEL",
    badge: "FINTECH · COINGECKO & BINANCE",
    stepsSummary: ["CoinGecko Tickers", "Binance 24h Ticker", "Volatility Router", "Quant Analyst Agent", "Telegram Dispatch"],
    instructions: "1. Fetch CoinGecko & Binance ticker data. 2. Evaluate price momentum delta. 3. Quant agent identifies arbitrage opportunities. 4. Dispatch Telegram alert.",
    inputSchema: { type: "object", properties: { assetIds: { type: "string" } } },
    outputSchema: { type: "object", properties: { momentumAnalysis: { type: "string" } } },
    examples: [{ input: { assetIds: "bitcoin,ethereum" }, output: { status: "DELIVERED" } }],
    allowedTools: ["http", "notification_dispatcher"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 6,
  },
  {
    id: "global_fx_inflation_monitor",
    name: "Global FX & Inflation Monitor",
    purpose: "Pulls live cross-currency foreign exchange rates from Frankfurter and macroeconomic inflation indicators from the World Bank to generate currency risk and hedging reports.",
    category: "FINANCE & INTEL",
    badge: "FINTECH · FRANKFURTER & WORLD BANK",
    stepsSummary: ["Frankfurter FX Rates", "World Bank CPI Indicator", "Macro Economist Analysis", "Executive FX Report"],
    instructions: "1. Ingest Frankfurter FX conversions. 2. Ingest World Bank inflation data. 3. Macro economist analyzes purchasing power parity. 4. Output strategy dossier.",
    inputSchema: { type: "object", properties: { baseCurrency: { type: "string" } } },
    outputSchema: { type: "object", properties: { fxReport: { type: "string" } } },
    examples: [{ input: { baseCurrency: "USD" }, output: { status: "COMPLETED" } }],
    allowedTools: ["http"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 5,
  },
  {
    id: "open_source_deep_research_studio",
    name: "Open-Source Deep Research & Report Studio",
    purpose: "Performs privacy-first web research via SearXNG, extracts clean markdown via Crawl4AI, synthesizes an executive brief, and compiles a publication-ready PDF via Gotenberg.",
    category: "OPEN SOURCE & SELF-HOSTED",
    badge: "OPEN SOURCE · SEARXNG + CRAWL4AI + GOTENBERG",
    stepsSummary: ["SearXNG Search", "Crawl4AI Markdown Scraper", "AI Research Scientist", "Gotenberg PDF Engine"],
    instructions: "1. Search for query topics on SearXNG. 2. Crawl top results to clean markdown. 3. Synthesize structured findings. 4. Compile PDF report.",
    inputSchema: { type: "object", properties: { query: { type: "string" } }, required: ["query"] },
    outputSchema: { type: "object", properties: { reportUrl: { type: "string" } } },
    examples: [{ input: { query: "Autonomous multi-agent patterns" }, output: { status: "GENERATED" } }],
    allowedTools: ["searxng_search", "crawl4ai_scrape", "gotenberg_pdf_exporter"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 6,
  },
  {
    id: "docling_paper_knowledge_pipeline",
    name: "Docling Paper & Document Knowledge Pipeline",
    purpose: "Ingests complex research PDFs or corporate documents with Docling (IBM), extracts structured tables and insights with an AI Analyst, and persists the structured record into NocoDB.",
    category: "OPEN SOURCE & SELF-HOSTED",
    badge: "OPEN SOURCE · DOCLING + NOCODB",
    stepsSummary: ["Docling PDF Parser", "Document Intel Agent", "NocoDB Knowledge Logger"],
    instructions: "1. Parse PDF document into structured tables and markdown. 2. Extract key conclusions and architecture diagrams. 3. Insert record into NocoDB table.",
    inputSchema: { type: "object", properties: { documentUrl: { type: "string" } }, required: ["documentUrl"] },
    outputSchema: { type: "object", properties: { recordId: { type: "string" } } },
    examples: [{ input: { documentUrl: "https://arxiv.org/pdf/1706.03762.pdf" }, output: { status: "INDEXED" } }],
    allowedTools: ["docling_pdf_parser", "nocodb_record"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 5,
  },
  {
    id: "voice_dispatcher_whisper_piper",
    name: "Multi-Agent Voice Dispatch & Transcription",
    purpose: "Transcribes customer voice recordings with Faster-Whisper, runs an AI Triage Agent to classify intent, synthesizes a voice response with Piper TTS, and dispatches alerts.",
    category: "OPEN SOURCE & SELF-HOSTED",
    badge: "LOCAL AI · FASTER-WHISPER + PIPER TTS",
    stepsSummary: ["Faster-Whisper STT", "Voice Triage Agent", "Piper TTS Synthesis", "Notification Broadcast"],
    instructions: "1. Transcribe voice recording into text. 2. Triage inquiry and formulate response. 3. Generate spoken audio with Piper. 4. Dispatch notification.",
    inputSchema: { type: "object", properties: { audioUrl: { type: "string" } }, required: ["audioUrl"] },
    outputSchema: { type: "object", properties: { audioResponseUrl: { type: "string" } } },
    examples: [{ input: { audioUrl: "https://example.com/ticket-voice.mp3" }, output: { status: "DISPATCHED" } }],
    allowedTools: ["audio_transcriber", "piper_tts", "notification_dispatcher"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 6,
  },
  {
    id: "qdrant_vector_memory_rag",
    name: "Vector Memory & Persistent Long-Term RAG",
    purpose: "Performs semantic recall over self-hosted Qdrant vector collections, grounds the AI reasoner with past conversation history, and stores state in PocketBase.",
    category: "OPEN SOURCE & SELF-HOSTED",
    badge: "SELF-HOSTED · QDRANT + POCKETBASE",
    stepsSummary: ["Qdrant Vector Recall", "Context Reasoner Agent", "PocketBase Session Store"],
    instructions: "1. Search relevant vector embeddings in Qdrant. 2. Ground prompt with retrieved chunks. 3. Save run state and answers into PocketBase collection.",
    inputSchema: { type: "object", properties: { query: { type: "string" } }, required: ["query"] },
    outputSchema: { type: "object", properties: { answer: { type: "string" } } },
    examples: [{ input: { query: "What are our compliance guidelines?" }, output: { status: "RECALLED_AND_SAVED" } }],
    allowedTools: ["qdrant_vector_memory", "pocketbase_store"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 5,
  },
  {
    id: "windmill_activepieces_orchestrator",
    name: "Windmill & Activepieces Distributed Orchestration",
    purpose: "Triggers self-hosted Windmill Python scripts or Activepieces webhooks on a schedule, evaluates data anomalies with a Router, and delegates remediation to an AI Operator.",
    category: "OPEN SOURCE & SELF-HOSTED",
    badge: "OPEN WORKFLOWS · CRON + HTTP + AGENT",
    stepsSummary: ["Cron Schedule Trigger", "Windmill/Activepieces API", "Health Router", "SRE Remediation Agent", "Slack Broadcast"],
    instructions: "1. Trigger background job. 2. Evaluate job status. 3. If anomaly detected, SRE agent fixes issue. 4. Broadcast summary.",
    inputSchema: { type: "object", properties: { jobName: { type: "string" } } },
    outputSchema: { type: "object", properties: { status: { type: "string" } } },
    examples: [{ input: { jobName: "sync_database" }, output: { status: "COMPLETED" } }],
    allowedTools: ["schedule_trigger", "http", "notification_dispatcher"],
    actionsRequiringApproval: [],
    maxExecutionSteps: 7,
  },
];
