import type { AgentGraphDefinition } from "@/types/graph";

// ─── Visual Export (PNG / SVG / PDF) ───

/**
 * Helper to trigger a browser download for a data URL.
 */
function downloadDataUrl(dataUrl: string, filename: string): void {
  const link = document.createElement("a");
  link.download = filename;
  link.href = dataUrl;
  link.click();
}

/**
 * Export the canvas viewport as a high-resolution PNG using html-to-image.
 * Dynamically imports the library to avoid SSR issues.
 */
export async function exportCanvasAsPng(
  containerRef: HTMLElement,
  filename = "agent-graph.png"
): Promise<void> {
  const { toPng } = await import("html-to-image");
  const dataUrl = await toPng(containerRef, {
    quality: 1.0,
    pixelRatio: 3,
    backgroundColor: "#07070d",
    style: { transform: "scale(1)", transformOrigin: "top left" },
  });
  downloadDataUrl(dataUrl, filename);
}

/**
 * Export the canvas viewport as an SVG.
 */
export async function exportCanvasAsSvg(
  containerRef: HTMLElement,
  filename = "agent-graph.svg"
): Promise<void> {
  const { toSvg } = await import("html-to-image");
  const dataUrl = await toSvg(containerRef, {
    backgroundColor: "#07070d",
  });
  downloadDataUrl(dataUrl, filename);
}

/**
 * Export the canvas viewport as a PDF using jsPDF + html-to-image.
 */
export async function exportCanvasAsPdf(
  containerRef: HTMLElement,
  filename = "agent-graph.pdf"
): Promise<void> {
  const [{ toPng }, { jsPDF }] = await Promise.all([
    import("html-to-image"),
    import("jspdf"),
  ]);
  const dataUrl = await toPng(containerRef, {
    quality: 1.0,
    pixelRatio: 2,
    backgroundColor: "#07070d",
  });
  const img = new Image();
  img.src = dataUrl;
  await new Promise<void>((resolve) => {
    img.onload = () => resolve();
  });
  const pdf = new jsPDF({
    orientation: img.width > img.height ? "landscape" : "portrait",
    unit: "px",
    format: [img.width, img.height],
  });
  pdf.addImage(dataUrl, "PNG", 0, 0, img.width, img.height);
  pdf.save(filename);
}

// ─── Mermaid.js Export ───

/**
 * Convert a graph definition into a Mermaid.js flowchart diagram string.
 * Uses `graph LR` (left-to-right) direction.
 */
export function graphToMermaid(graph: AgentGraphDefinition): string {
  const lines: string[] = ["graph LR"];

  const nodeLabels = graph.nodes.map((n) => {
    const id = n.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const label = n.data.label || n.id;
    switch (n.type) {
      case "start":
        return `  ${id}([Start: ${label}])`;
      case "end":
        return `  ${id}([End: ${label}])`;
      case "agent":
        return `  ${id}["Agent: ${label}"]`;
      case "supervisor":
        return `  ${id}{"Supervisor: ${label}"}`;
      case "tool":
        return `  ${id}["Tool: ${label}"]`;
      case "router":
        return `  ${id}{"Router: ${label}"}`;
      case "approval":
        return `  ${id}["Approval: ${label}"]`;
      case "loop":
        return `  ${id}{"Loop: ${label}"}`;
      case "parallel":
        return `  ${id}{"Parallel: ${label}"}`;
      case "subgraph":
        return `  ${id}["Subgraph: ${label}"]`;
      case "sticky_note":
        return `  ${id}["Note: ${label}"]:::note`;
      case "frame":
        return `  ${id}["Frame: ${label}"]:::frame`;
      default:
        return `  ${id}["${label}"]`;
    }
  });

  lines.push(...nodeLabels);

  // Edges
  const edgeLines = graph.edges.map((e) => {
    const src = e.source.replace(/[^a-zA-Z0-9_]/g, "_");
    const tgt = e.target.replace(/[^a-zA-Z0-9_]/g, "_");
    if (e.label) {
      return `  ${src} -->|"${e.label}"| ${tgt}`;
    }
    return `  ${src} --> ${tgt}`;
  });

  lines.push("");
  lines.push(...edgeLines);

  // Class definitions
  lines.push("");
  lines.push("  classDef note fill:#fef3c7,stroke:#f59e0b,stroke-width:1px,color:#92400e");
  lines.push("  classDef frame fill:#e0e7ff,stroke:#6366f1,stroke-width:1px,color:#3730a3");

  return lines.join("\n");
}

// ─── LangGraph (Python) Export ───

/**
 * Convert a graph definition into a LangGraph Python code string.
 * Generates a StateGraph with typed nodes and conditional edges.
 */
export function graphToLangGraphPython(graph: AgentGraphDefinition): string {
  const SKIP = new Set(["start", "end", "sticky_note", "frame"]);
  const _Q = '"'; // Python double-quote character
  const lines: string[] = [];

  // File header
  lines.push('"""');
  lines.push("Auto-generated LangGraph agent graph.");
  lines.push("Generated by Agent Studio — https://agentstudio.dev");
  lines.push('"""');
  lines.push("");
  lines.push("from typing import TypedDict, Annotated, Any");
  lines.push("import asyncio");
  lines.push("import json");
  lines.push("from langgraph.graph import StateGraph, END");
  lines.push("from langgraph.graph.message import add_messages");
  lines.push("");
  lines.push("");
  lines.push("# ── State Schema ──");
  lines.push("class AgentState(TypedDict):");
  lines.push("    input: Any");
  lines.push("    results: dict[str, Any]");
  lines.push("    messages: Annotated[list, add_messages]");
  lines.push("");
  lines.push("");
  lines.push("# ── Node Functions ──");

  for (const node of graph.nodes) {
    if (SKIP.has(node.type)) continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const prompt = node.data.prompt ?? "";
    const nodeId = node.id;
    const label = node.data.label;

    lines.push("async def " + funcName + "(state: AgentState) -> dict:");

    switch (node.type) {
      case "agent":
        lines.push('    """' + label + ": LLM agent node\"\"\"");
        lines.push("    # LLM call — replace with your provider (OpenAI, Anthropic, etc.)");
        lines.push("    import openai");
        lines.push("    client = openai.AsyncOpenAI()");
        lines.push("    response = await client.chat.completions.create(");
        lines.push('        model="gpt-4o-mini",');
        lines.push("        messages=[");
        lines.push('            {"role": "system", "content": ' + JSON.stringify(prompt.slice(0, 200)) + "},");
        lines.push('            {"role": "user", "content": json.dumps({"context": state.get("results", {}), "input": state.get("input", {})})},');
        lines.push("        ],");
        lines.push("        temperature=0.2,");
        lines.push("    )");
        lines.push("    output = response.choices[0].message.content");
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "supervisor":
        lines.push('    """' + label + ': Supervisor router — LLM picks next step"""');
        lines.push("    import openai");
        lines.push("    client = openai.AsyncOpenAI()");
        const choices = JSON.stringify(
          graph.edges.filter((e) => e.source === node.id).map((e) => e.label || e.target)
        );
        lines.push("    choices = " + choices);
        lines.push("    response = await client.chat.completions.create(");
        lines.push('        model="gpt-4o-mini",');
        lines.push("        messages=[");
        lines.push('            {"role": "system", "content": f"Choose the next step from: {choices}. Respond with JSON: {\\\"next\\\": \\\"<choice>\\\"}"},');
        lines.push('            {"role": "user", "content": json.dumps(state.get("results", {}))},');
        lines.push("        ],");
        lines.push("        temperature=0.0,");
        lines.push("    )");
        lines.push("    parsed = json.loads(response.choices[0].message.content)");
        lines.push('    route = parsed.get("next", choices[0])');
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": route}, "route": route}');
        break;

      case "tool":
        lines.push('    """Tool: ' + (node.data.toolName ?? "unknown") + " / " + (node.data.action ?? "") + '"""');
        lines.push("    # Tool execution — implement based on the tool type");
        lines.push("    tool_input = " + JSON.stringify(node.data.inputTemplate ?? {}) + "  # resolved at runtime");
        lines.push('    # Example: await execute_tool("' + (node.data.toolName ?? "tool") + '", tool_input)');
        lines.push('    output = {"action": "' + (node.data.action ?? "run") + '", "input": tool_input, "result": "TODO: implement tool"}');
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "router": {
        const mode = node.data.routerMode === "ai" ? "AI-based" : "condition: " + (node.data.condition ?? "");
        lines.push('    """Router: ' + mode + '"""');
        if (node.data.routerMode === "ai") {
          lines.push("    # AI router — delegate to LLM to pick a branch");
          lines.push('    route = state.get("route", "")  # set by supervisor or previous AI router');
        } else {
          lines.push("    # Deterministic condition: " + (node.data.condition ?? ""));
          lines.push('    results = state.get("results", {})');
          lines.push("    # Evaluate: " + (node.data.condition ?? "True"));
          lines.push('    route = "true"  # TODO: evaluate condition expression');
        }
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": {"route": route}}, "route": route}');
        break;
      }

      case "approval":
        lines.push('    """HITL approval gate: ' + (node.data.approvalReason ?? "Review required") + '"""');
        lines.push("    # Human-in-the-loop: pause and wait for approval");
        lines.push("    # In production, integrate with your approval system");
        lines.push('    print("[APPROVAL REQUIRED] ' + (node.data.approvalReason ?? "Review needed") + '")');
        lines.push('    approval = input("Approve? (y/n): ")  # Replace with async approval flow');
        lines.push('    if approval.lower() != "y":');
        lines.push('        raise Exception("Approval rejected")');
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": {"approved": True}}}');
        break;

      case "loop":
        lines.push('    """Loop controller: max ' + (node.data.maxIterations ?? 3) + ' iterations"""');
        lines.push('    counter = state.get("loop_counters", {}).get("' + nodeId + '", 0) + 1');
        lines.push("    max_iter = " + (node.data.maxIterations ?? 3));
        lines.push("    exit_loop = counter > max_iter");
        lines.push('    loop_counters = {**state.get("loop_counters", {}), "' + nodeId + '": counter}');
        lines.push('    route = "exit" if exit_loop else "body"');
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": {"iteration": counter, "exited": exit_loop}}, "loop_counters": loop_counters, "route": route}');
        break;

      case "transform":
        lines.push('    """Transform: ' + (node.data.transformOp ?? "map") + " " + (node.data.transformExpr ?? "") + '"""');
        lines.push('    results = state.get("results", {})');
        lines.push("    # Get input from the previous node");
        lines.push("    input_data = list(results.values())[-1] if results else None");
        lines.push("    if isinstance(input_data, list):");
        if (node.data.transformOp === "map") {
          lines.push("        output = [item.get('" + (node.data.transformExpr ?? "name") + "') if isinstance(item, dict) else item for item in input_data]");
        } else if (node.data.transformOp === "filter") {
          lines.push("        output = [item for item in input_data if item]");
        } else if (node.data.transformOp === "flatten") {
          lines.push("        output = [x for sublist in input_data for x in (sublist if isinstance(sublist, list) else [sublist])]");
        } else if (node.data.transformOp === "sort") {
          lines.push("        output = sorted(input_data, key=lambda x: str(x))");
        } else if (node.data.transformOp === "dedupe") {
          lines.push("        seen = set(); output = [x for x in input_data if not (str(x) in seen or seen.add(str(x)))]");
        } else {
          lines.push("        output = input_data  # " + (node.data.transformOp ?? "map"));
        }
        lines.push("    else:");
        lines.push("        output = input_data");
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "aggregate":
        lines.push('    """Aggregate: ' + (node.data.aggregateMode ?? "concat") + '"""');
        lines.push('    results = state.get("results", {})');
        lines.push('    branch_results = [v for k, v in results.items() if k != "' + nodeId + '"]');
        if (node.data.aggregateMode === "concat") {
          lines.push("    output = []");
          lines.push("    for r in branch_results:");
          lines.push("        if isinstance(r, list): output.extend(r)");
          lines.push("        else: output.append(r)");
        } else if (node.data.aggregateMode === "merge") {
          lines.push("    output = {}");
          lines.push("    for r in branch_results:");
          lines.push("        if isinstance(r, dict): output.update(r)");
        } else if (node.data.aggregateMode === "count") {
          lines.push('    output = {"count": len(branch_results), "items": branch_results}');
        } else if (node.data.aggregateMode === "first") {
          lines.push("    output = branch_results[0] if branch_results else None");
        } else {
          lines.push("    output = branch_results");
        }
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "variable":
        lines.push('    """Variable: ' + (node.data.varOp ?? "get") + " " + (node.data.varName ?? "") + '"""');
        lines.push('    variables = state.get("variables", {})');
        if (node.data.varOp === "set") {
          lines.push('    variables["' + (node.data.varName ?? "var") + '"] = ' + JSON.stringify(node.data.varValue ?? null));
          lines.push('    return {"variables": variables}');
        } else {
          lines.push('    output = variables.get("' + (node.data.varName ?? "var") + '", None)');
          lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        }
        break;

      case "output":
        lines.push('    """Output formatter"""');
        lines.push('    results = state.get("results", {})');
        if (node.data.outputFields && Object.keys(node.data.outputFields).length > 0) {
          lines.push("    # Field mapping output");
          lines.push("    output = {}");
          for (const [key, template] of Object.entries(node.data.outputFields)) {
            lines.push('    output["' + key + '"] = results  # TODO: resolve template ' + template);
          }
        } else {
          lines.push("    output = results");
        }
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "http":
        lines.push('    """HTTP Request: ' + (node.data.httpMethod ?? "GET") + " " + (node.data.httpUrl ?? "") + '"""');
        lines.push("    import aiohttp");
        lines.push("    async with aiohttp.ClientSession() as session:");
        lines.push('        method = "' + (node.data.httpMethod ?? "GET") + '"');
        lines.push('        url = "' + (node.data.httpUrl ?? "") + '"');
        lines.push("        headers = " + JSON.stringify(node.data.httpHeaders ?? {}));
        lines.push("        body = " + JSON.stringify(node.data.httpBody ?? null));
        lines.push("        async with session.request(method, url, headers=headers, json=body) as resp:");
        lines.push('            output = await resp.json() if "json" in resp.content_type else await resp.text()');
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "delay":
        lines.push('    """Delay: wait ' + (node.data.delayMs ?? 1000) + 'ms"""');
        lines.push("    await asyncio.sleep(" + ((node.data.delayMs ?? 1000) / 1000) + ")");
        lines.push("    return state");
        break;

      case "mcp_server":
        lines.push('    """MCP Server: ' + (node.data.mcpServerId ?? "unknown") + '"""');
        lines.push("    # MCP server connection — configure via MCP SDK");
        lines.push("    return state");
        break;

      case "mcp_tool":
        lines.push('    """MCP Tool: ' + (node.data.mcpToolName ?? "unknown") + " from " + (node.data.mcpToolServer ?? "unknown") + '"""');
        lines.push("    # MCP tool call — use the MCP SDK client");
        lines.push("    output = " + JSON.stringify({ mcp_tool: node.data.mcpToolName ?? "", server: node.data.mcpToolServer ?? "" }));
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      case "skill":
        lines.push('    """Skill: ' + (node.data.skillId ?? "unknown") + '"""');
        lines.push("    # Sub-skill invocation — call the Agent Studio API");
        lines.push("    import aiohttp");
        lines.push("    async with aiohttp.ClientSession() as session:");
        lines.push('        async with session.post("YOUR_API_URL/api/executions", json={"skillVersionId": "' + (node.data.skillId ?? "") + '", "inputData": state.get("input", {})}) as resp:');
        lines.push("            output = await resp.json()");
        lines.push('    return {"results": {**state.get("results", {}), "' + nodeId + '": output}}');
        break;

      default:
        lines.push('    """' + label + '"""');
        lines.push("    return state");
    }
    lines.push("");
  }

  // Build the graph
  lines.push("# ── Graph Construction ──");
  lines.push("graph = StateGraph(AgentState)");

  for (const node of graph.nodes) {
    if (SKIP.has(node.type)) continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push('graph.add_node("' + node.id + '", ' + funcName + ")");
  }

  // Entry point
  const startNode = graph.nodes.find((n) => n.type === "start");
  if (startNode) {
    const startEdges = graph.edges.filter((e) => e.source === startNode.id);
    for (const e of startEdges) {
      lines.push('graph.set_entry_point("' + e.target + '")');
    }
  }

  // Collect conditional sources (routers, supervisors, loops)
  const conditionalSources = new Set<string>();
  for (const edge of graph.edges) {
    const source = graph.nodes.find((n) => n.id === edge.source);
    const target = graph.nodes.find((n) => n.id === edge.target);
    if (!source || !target) continue;
    if (target.type === "end") {
      lines.push('graph.add_edge("' + edge.source + '", END)');
    } else if (source.type === "router" || source.type === "supervisor" || source.type === "loop") {
      conditionalSources.add(edge.source);
    } else {
      lines.push('graph.add_edge("' + edge.source + '", "' + edge.target + '")');
    }
  }

  // Add conditional edges
  for (const srcId of conditionalSources) {
    const outEdges = graph.edges.filter((e) => e.source === srcId);
    const mappingEntries: string[] = [];
    const endId = graph.nodes.find((n) => n.type === "end")?.id;
    for (const e of outEdges) {
      const label = e.label || "default";
      const target = e.target === endId ? "END" : e.target;
      mappingEntries.push('"' + label + '": "' + target + '"');
    }
    lines.push(
      'graph.add_conditional_edges("' + srcId + '", lambda s: s.get("route", ""), {' + mappingEntries.join(", ") + "})"
    );
  }

  lines.push("");
  lines.push("# Compile the graph");
  lines.push("app = graph.compile()");
  lines.push("");
  lines.push("# ── Run the graph ──");
  lines.push('if __name__ == "__main__":');
  lines.push('    result = asyncio.run(app.ainvoke({"input": {}, "results": {}}))');
  lines.push("    print(json.dumps(result, indent=2, default=str))");
  lines.push("");

  return lines.join("\n");
}

// ─── LangGraph (TypeScript) Export ───

/**
 * Convert a graph definition into a LangGraph TypeScript code string.
 */
export function graphToLangGraphTS(graph: AgentGraphDefinition): string {
  const SKIP = new Set(["start", "end", "sticky_note", "frame"]);
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * Auto-generated LangGraph agent graph.");
  lines.push(" * Generated by Agent Studio — https://agentstudio.dev");
  lines.push(" */");
  lines.push("");
  lines.push('import { StateGraph, Annotation, END } from "@langchain/langgraph";');
  lines.push('import { ChatOpenAI } from "@langchain/openai";');
  lines.push("");
  lines.push('const llm = new ChatOpenAI({ model: "gpt-4o-mini", temperature: 0.2 });');
  lines.push("");
  lines.push("");
  lines.push("// ── State Annotation ──");
  lines.push("const AgentState = Annotation.Root({");
  lines.push("  input: Annotation<Record<string, any>>");
  lines.push("  results: Annotation<Record<string, any>>({");
  lines.push('    reducer: (prev, curr) => ({ ...prev, ...curr }),');
  lines.push('    default: () => ({}),');
  lines.push("  }),");
  lines.push("  route: Annotation<string>");
  lines.push("});");
  lines.push("");
  lines.push("");
  lines.push("// ── Node Functions ──");

  for (const node of graph.nodes) {
    if (SKIP.has(node.type)) continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const prompt = node.data.prompt ?? "";
    const nodeId = node.id;
    const label = node.data.label;

    lines.push("async function " + funcName + "(state: typeof AgentState.State) {");

    switch (node.type) {
      case "agent":
        lines.push("  // " + label + ": LLM agent");
        lines.push("  const response = await llm.invoke([");
        lines.push("    { role: \"system\", content: " + JSON.stringify(prompt.slice(0, 200)) + " },");
        lines.push("    { role: \"user\", content: JSON.stringify({ context: state.results, input: state.input }) },");
        lines.push("  ]);");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": response.content } };");
        break;

      case "supervisor": {
        const choices = JSON.stringify(
          graph.edges.filter((e) => e.source === node.id).map((e) => e.label || e.target)
        );
        lines.push("  // " + label + ": Supervisor router");
        lines.push("  const choices = " + choices + ";");
        lines.push("  const response = await llm.invoke([");
        lines.push("    { role: \"system\", content: `Choose the next step from: ${choices.join(\", \")}. Respond with JSON: {\"next\": \"<choice>\"}` },");
        lines.push("    { role: \"user\", content: JSON.stringify(state.results) },");
        lines.push("  ]);");
        lines.push("  const parsed = JSON.parse(response.content as string);");
        lines.push("  const route = parsed.next ?? choices[0];");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": route }, route };");
        break;
      }

      case "tool":
        lines.push("  // " + label + ": Tool " + (node.data.toolName ?? "unknown"));
        lines.push("  const toolInput = " + JSON.stringify(node.data.inputTemplate ?? {}) + ";");
        lines.push("  // TODO: wire up your tool execution layer");
        lines.push("  const output = { action: \"" + (node.data.action ?? "run") + "\", input: toolInput };");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        break;

      case "router":
        lines.push("  // " + label + ": Router");
        if (node.data.routerMode === "ai") {
          lines.push("  const route = state.route ?? \"\";");
        } else {
          lines.push("  // Condition: " + (node.data.condition ?? ""));
          lines.push("  const route = \"true\"; // TODO: evaluate condition");
        }
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": { route } }, route };");
        break;

      case "approval":
        lines.push("  // " + label + ": HITL approval");
        lines.push("  console.log(\"[APPROVAL REQUIRED] " + (node.data.approvalReason ?? "Review needed") + "\");");
        lines.push("  // TODO: integrate with your approval system");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": { approved: true } } };");
        break;

      case "loop":
        lines.push("  // " + label + ": Loop (max " + (node.data.maxIterations ?? 3) + ")");
        lines.push("  const counter = (state.loopCounters?.[\"" + nodeId + "\"] ?? 0) + 1;");
        lines.push("  const exited = counter > " + (node.data.maxIterations ?? 3) + ";");
        lines.push("  const route = exited ? \"exit\" : \"body\";");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": { iteration: counter, exited } }, route, loopCounters: { ...state.loopCounters, \"" + nodeId + "\": counter } };");
        break;

      case "transform":
        lines.push("  // " + label + ": Transform (" + (node.data.transformOp ?? "map") + ")");
        lines.push("  const input = Object.values(state.results).pop();");
        lines.push("  const output = Array.isArray(input) ? input : [input];");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        break;

      case "aggregate":
        lines.push("  // " + label + ": Aggregate (" + (node.data.aggregateMode ?? "concat") + ")");
        lines.push("  const values = Object.values(state.results);");
        lines.push("  const output = values.flat();");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        break;

      case "variable":
        lines.push("  // " + label + ": Variable " + (node.data.varOp ?? "get") + " " + (node.data.varName ?? ""));
        if (node.data.varOp === "set") {
          lines.push("  const variables = { ...state.variables, \"" + (node.data.varName ?? "var") + "\": " + JSON.stringify(node.data.varValue ?? null) + " };");
          lines.push("  return { variables };");
        } else {
          lines.push("  const output = state.variables?.[\"" + (node.data.varName ?? "var") + "\"] ?? null;");
          lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        }
        break;

      case "output":
        lines.push("  // " + label + ": Output formatter");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": state.results } };");
        break;

      case "http":
        lines.push("  // " + label + ": HTTP " + (node.data.httpMethod ?? "GET") + " " + (node.data.httpUrl ?? ""));
        lines.push("  const resp = await fetch(\"" + (node.data.httpUrl ?? "") + "\", {");
        lines.push("    method: \"" + (node.data.httpMethod ?? "GET") + "\",");
        lines.push("    headers: " + JSON.stringify(node.data.httpHeaders ?? {}) + ",");
        if (node.data.httpBody) {
          lines.push("    body: JSON.stringify(" + JSON.stringify(node.data.httpBody) + "),");
        }
        lines.push("  });");
        lines.push("  const output = await resp.json();");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        break;

      case "delay":
        lines.push("  // " + label + ": Delay " + (node.data.delayMs ?? 1000) + "ms");
        lines.push("  await new Promise(r => setTimeout(r, " + (node.data.delayMs ?? 1000) + "));");
        lines.push("  return state;");
        break;

      case "mcp_server":
        lines.push("  // " + label + ": MCP Server " + (node.data.mcpServerId ?? ""));
        lines.push("  return state;");
        break;

      case "mcp_tool":
        lines.push("  // " + label + ": MCP Tool " + (node.data.mcpToolName ?? ""));
        lines.push("  const output = { mcpTool: \"" + (node.data.mcpToolName ?? "") + "\", server: \"" + (node.data.mcpToolServer ?? "") + "\" };");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        break;

      case "skill":
        lines.push("  // " + label + ": Skill invocation");
        lines.push("  const resp = await fetch(\"YOUR_API_URL/api/executions\", {");
        lines.push("    method: \"POST\",");
        lines.push("    headers: { \"Content-Type\": \"application/json\" },");
        lines.push("    body: JSON.stringify({ skillVersionId: \"" + (node.data.skillId ?? "") + "\", inputData: state.input }),");
        lines.push("  });");
        lines.push("  const output = await resp.json();");
        lines.push("  return { results: { ...state.results, \"" + nodeId + "\": output } };");
        break;

      default:
        lines.push("  // " + label);
        lines.push("  return state;");
    }
    lines.push("}");
    lines.push("");
  }

  lines.push("// ── Graph Construction ──");
  lines.push("const graph = new StateGraph(AgentState)");

  for (const node of graph.nodes) {
    if (SKIP.has(node.type)) continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push('  .addNode("' + node.id + '", ' + funcName + ")");
  }

  const startTarget = graph.edges.find((e) => e.source === startNodeId(graph))?.target ?? "END";
  lines.push("  .addEdge('__start__', '" + startTarget + "')");

  // Collect conditional sources
  const conditionalSources = new Set<string>();
  for (const edge of graph.edges) {
    const source = graph.nodes.find((n) => n.id === edge.source);
    if (!source || source.type === "start") continue;
    const target = graph.nodes.find((n) => n.id === edge.target);
    if (!target) continue;
    if (target.type === "end") {
      lines.push('  .addEdge("' + edge.source + '", END)');
    } else if (source.type === "router" || source.type === "supervisor" || source.type === "loop") {
      conditionalSources.add(edge.source);
    } else {
      lines.push('  .addEdge("' + edge.source + '", "' + edge.target + '")');
    }
  }

  // Conditional edges
  for (const srcId of conditionalSources) {
    const outEdges = graph.edges.filter((e) => e.source === srcId);
    const mappingEntries: string[] = [];
    const endId = graph.nodes.find((n) => n.type === "end")?.id;
    for (const e of outEdges) {
      const label = e.label || "default";
      const target = e.target === endId ? "__end__" : e.target;
      mappingEntries.push('"' + label + '": "' + target + '"');
    }
    lines.push('  .addConditionalEdges("' + srcId + '", (state) => state.route ?? "", {' + mappingEntries.join(", ") + "})");
  }

  lines.push("  .compile();");
  lines.push("");
  lines.push("export default app;");
  lines.push("");
  lines.push("// ── Run ──");
  lines.push("// const result = await app.invoke({ input: {}, results: {} });");
  lines.push("// console.log(result);");
  lines.push("");

  return lines.join("\n");
}

function startNodeId(graph: AgentGraphDefinition): string {
  return graph.nodes.find((n) => n.type === "start")?.id ?? "";
}

// ─── JSON Import/Export (already exists, but add a typed wrapper) ───

export function exportGraphAsJson(graph: AgentGraphDefinition): string {
  return JSON.stringify(graph, null, 2);
}

export function importGraphFromJson(jsonStr: string): AgentGraphDefinition | null {
  try {
    const data = JSON.parse(jsonStr);
    if (data && data.version === 1 && Array.isArray(data.nodes) && Array.isArray(data.edges)) {
      return data as AgentGraphDefinition;
    }
    return null;
  } catch {
    return null;
  }
}

// ─── Export Dialog Data ───

export interface ExportFormat {
  id: string;
  label: string;
  description: string;
  category: "visual" | "code" | "data";
  icon: string;
  extension: string;
}

export const EXPORT_FORMATS: ExportFormat[] = [
  { id: "png", label: "PNG Image", description: "High-resolution raster image (3x)", category: "visual", icon: "png", extension: ".png" },
  { id: "svg", label: "SVG Vector", description: "Scalable vector graphic", category: "visual", icon: "svg", extension: ".svg" },
  { id: "pdf", label: "PDF Document", description: "Print-ready document", category: "visual", icon: "pdf", extension: ".pdf" },
  { id: "mermaid", label: "Mermaid.js", description: "Flowchart diagram code", category: "code", icon: "mermaid", extension: ".md" },
  { id: "langgraph-py", label: "LangGraph Python", description: "Python StateGraph code", category: "code", icon: "python", extension: ".py" },
  { id: "langgraph-ts", label: "LangGraph TypeScript", description: "TypeScript StateGraph code", category: "code", icon: "typescript", extension: ".ts" },
  { id: "json", label: "JSON Schema", description: "Graph definition (import/export)", category: "data", icon: "json", extension: ".json" },
];
