import type { CanvasNode } from "./graphUtils";
import type { Edge } from "@xyflow/react";
import type { AgentGraphDefinition } from "@/types/graph";

// ─── Visual Export (PNG / SVG / PDF) ───

/**
 * Export the canvas viewport as a high-resolution PNG using html-to-image.
 * Dynamically imports the library to avoid SSR issues.
 */
export async function exportCanvasAsPng(
  containerRef: HTMLElement,
  filename = "agent-graph.png"
): Promise<void> {
  const { toPng } = await import("html-to-image");
  const dataUrl = await toPng(containerRef, {
    quality: 1.0,
    pixelRatio: 3,
    backgroundColor: "#07070d",
    style: { transform: "scale(1)", transformOrigin: "top left" },
  });
  downloadDataUrl(dataUrl, filename);
}

/**
 * Export the canvas viewport as an SVG.
 */
export async function exportCanvasAsSvg(
  containerRef: HTMLElement,
  filename = "agent-graph.svg"
): Promise<void> {
  const { toSvg } = await import("html-to-image");
  const dataUrl = await toSvg(containerRef, {
    backgroundColor: "#07070d",
  });
  downloadDataUrl(dataUrl, filename);
}

/**
 * Export the canvas viewport as a PDF using jsPDF + html-to-image.
 */
export async function exportCanvasAsPdf(
  containerRef: HTMLElement,
  filename = "agent-graph.pdf"
): Promise<void> {
  const [{ toPng }, { jsPDF }] = await Promise.all([
    import("html-to-image"),
    import("jspdf"),
  ]);
  const dataUrl = await toPng(containerRef, {
    quality: 1.0,
    pixelRatio: 2,
    backgroundColor: "#07070d",
  });
  const img = new Image();
  img.src = dataUrl;
  await new Promise<void>((resolve) => {
    img.onload = () => resolve();
  });
  const pdf = new jsPDF({
    orientation: img.width > img.height ? "landscape" : "portrait",
    unit: "px",
    format: [img.width, img.height],
  });
  pdf.addImage(dataUrl, "PNG", 0, 0, img.width, img.height);
  pdf.save(filename);
}

// ─── Mermaid.js Export ───

/**
 * Convert a graph definition into a Mermaid.js flowchart diagram string.
 * Uses `graph LR` (left-to-right) direction.
 */
export function graphToMermaid(graph: AgentGraphDefinition): string {
  const lines: string[] = ["graph LR"];

  const nodeLabels = graph.nodes.map((n) => {
    const id = n.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const label = n.data.label || n.id;
    switch (n.type) {
      case "start":
        return `  ${id}([🟢 ${label}])`;
      case "end":
        return `  ${id}([🔴 ${label}])`;
      case "agent":
        return `  ${id}["🤖 ${label}"]`;
      case "supervisor":
        return `  ${id}{"🔀 ${label}"}`;
      case "tool":
        return `  ${id}["🔧 ${label}"]`;
      case "router":
        return `  ${id}{"❓ ${label}"}`;
      case "approval":
        return `  ${id}["🛡️ ${label}"]`;
      case "loop":
        return `  ${id}{"🔁 ${label}"}`;
      case "parallel":
        return `  ${id}{"⚡ ${label}"}`;
      case "subgraph":
        return `  ${id}["📦 ${label}"]`;
      case "sticky_note":
        return `  ${id}["📝 ${label}"]:::note`;
      case "frame":
        return `  ${id}["📐 ${label}"]:::frame`;
      default:
        return `  ${id}["${label}"]`;
    }
  });

  lines.push(...nodeLabels);

  // Edges
  const edgeLines = graph.edges.map((e) => {
    const src = e.source.replace(/[^a-zA-Z0-9_]/g, "_");
    const tgt = e.target.replace(/[^a-zA-Z0-9_]/g, "_");
    if (e.label) {
      return `  ${src} -->|"${e.label}"| ${tgt}`;
    }
    return `  ${src} --> ${tgt}`;
  });

  lines.push("");
  lines.push(...edgeLines);

  // Class definitions
  lines.push("");
  lines.push("  classDef note fill:#fef3c7,stroke:#f59e0b,stroke-width:1px,color:#92400e");
  lines.push("  classDef frame fill:#e0e7ff,stroke:#6366f1,stroke-width:1px,color:#3730a3");

  return lines.join("\n");
}

// ─── LangGraph (Python) Export ───

/**
 * Convert a graph definition into a LangGraph Python code string.
 * Generates a StateGraph with typed nodes and conditional edges.
 */
export function graphToLangGraphPython(graph: AgentGraphDefinition): string {
  const lines: string[] = [
    '"""',
    "Auto-generated LangGraph agent graph.",
    "Generated by Agent Studio — https://agentstudio.dev",
    '"""',
    "",
    "from typing import TypedDict, Annotated, Any",
    "from langgraph.graph import StateGraph, END",
    "from langgraph.graph.message import add_messages",
    "",
    "",
    "# ── State Schema ──",
    "class AgentState(TypedDict):",
    "    input: Any",
    "    results: dict[str, Any]",
    "    messages: Annotated[list, add_messages]",
    "",
    "",
    "# ── Node Functions ──",
  ];

  for (const node of graph.nodes) {
    if (node.type === "start" || node.type === "end" || node.type === "sticky_note" || node.type === "frame") continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const prompt = node.data.prompt ?? "";
    lines.push(`async def ${funcName}(state: AgentState) -> dict:`);
    if (node.type === "agent" || node.type === "supervisor") {
      lines.push(`    """${node.data.label}: ${prompt.slice(0, 100)}"""`);
      lines.push(`    # TODO: Implement LLM call`);
      lines.push(`    return {"results": {**state.get("results", {}), "${node.id}": {}}}`);
    } else if (node.type === "tool") {
      lines.push(`    """Tool: ${node.data.toolName ?? "unknown"} / ${node.data.action ?? ""}"""`);
      lines.push(`    # TODO: Implement tool call`);
      lines.push(`    return {"results": {**state.get("results", {}), "${node.id}": {}}}`);
    } else if (node.type === "router") {
      lines.push(`    """Router: ${node.data.routerMode === "ai" ? "AI-based" : `condition: ${node.data.condition ?? ""}`}"""`);
      lines.push(`    return state`);
    } else if (node.type === "approval") {
      lines.push(`    """Approval gate: ${node.data.approvalReason ?? ""}"""`);
      lines.push(`    # TODO: Implement HITL approval`);
      lines.push(`    return state`);
    } else if (node.type === "loop") {
      lines.push(`    """Loop: max ${node.data.maxIterations ?? 3} iterations"""`);
      lines.push(`    return state`);
    } else if (node.type === "transform") {
      lines.push(`    """Transform: ${node.data.transformOp ?? "map"} ${node.data.transformExpr ?? ""}"""`);
      lines.push(`    return state`);
    } else if (node.type === "aggregate") {
      lines.push(`    """Aggregate: ${node.data.aggregateMode ?? "concat"}"""`);
      lines.push(`    return state`);
    } else {
      lines.push(`    """${node.data.label}"""`);
      lines.push(`    return state`);
    }
    lines.push("");
  }

  // Build the graph
  lines.push("# ── Graph Construction ──");
  lines.push("graph = StateGraph(AgentState)");

  for (const node of graph.nodes) {
    if (node.type === "start" || node.type === "end" || node.type === "sticky_note" || node.type === "frame") continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push(`graph.add_node("${node.id}", ${funcName})`);
  }

  // Entry point
  const startNode = graph.nodes.find((n) => n.type === "start");
  if (startNode) {
    // Connect start to its targets
    const startEdges = graph.edges.filter((e) => e.source === startNode.id);
    for (const e of startEdges) {
      lines.push(`graph.set_entry_point("${e.target}")`);
    }
  }

  // Edges
  for (const edge of graph.edges) {
    const source = graph.nodes.find((n) => n.id === edge.source);
    const target = graph.nodes.find((n) => n.id === edge.target);
    if (!source || !target) continue;
    if (target.type === "end") {
      lines.push(`graph.add_edge("${edge.source}", END)`);
    } else if (source.type === "router" || source.type === "supervisor") {
      if (edge.label) {
        lines.push(`graph.add_conditional_edges("${edge.source}", lambda s: s.get("route", ""), {"${edge.label}": "${edge.target}"})`);
      }
    } else {
      lines.push(`graph.add_edge("${edge.source}", "${edge.target}")`);
    }
  }

  lines.push("");
  lines.push("# Compile the graph");
  lines.push("app = graph.compile()");
  lines.push("");

  return lines.join("\n");
}

// ─── LangGraph (TypeScript) Export ───

/**
 * Convert a graph definition into a LangGraph TypeScript code string.
 */
export function graphToLangGraphTS(graph: AgentGraphDefinition): string {
  const lines: string[] = [
    "/**",
    " * Auto-generated LangGraph agent graph.",
    " * Generated by Agent Studio — https://agentstudio.dev",
    " */",
    "",
    'import { StateGraph, Annotation, END } from "@langchain/langgraph";',
    "",
    "",
    "// ── State Annotation ──",
    "const AgentState = Annotation.Root({",
    "  input: Annotation<string>,",
    "  results: Annotation<Record<string, any>>({",
    '    reducer: (prev, curr) => ({ ...prev, ...curr }),',
    '    default: () => ({}),',
    "  }),",
    "});",
    "",
    "",
    "// ── Node Functions ──",
  ];

  for (const node of graph.nodes) {
    if (node.type === "start" || node.type === "end" || node.type === "sticky_note" || node.type === "frame") continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push(`async function ${funcName}(state: typeof AgentState.State) {`);
    lines.push(`  // ${node.data.label}`);
    lines.push(`  return state.results;`);
    lines.push(`}`);
    lines.push("");
  }

  lines.push("// ── Graph Construction ──");
  lines.push("const graph = new StateGraph(AgentState)");

  for (const node of graph.nodes) {
    if (node.type === "start" || node.type === "end" || node.type === "sticky_note" || node.type === "frame") continue;
    const funcName = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push(`  .addNode("${node.id}", ${funcName})`);
  }

  lines.push("  .addEdge('__start__', '" + (graph.edges.find((e) => e.source === startNodeId(graph))?.target ?? "END") + "')");

  for (const edge of graph.edges) {
    const source = graph.nodes.find((n) => n.id === edge.source);
    if (!source || source.type === "start") continue;
    const target = graph.nodes.find((n) => n.id === edge.target);
    if (!target) continue;
    if (target.type === "end") {
      lines.push(`  .addEdge("${edge.source}", END)`);
    } else if (source.type === "router" && edge.label) {
      // Router conditional edges handled separately
    } else {
      lines.push(`  .addEdge("${edge.source}", "${edge.target}")`);
    }
  }

  lines.push("  .compile();");
  lines.push("");
  lines.push("export default app;");

  return lines.join("\n");
}

function startNodeId(graph: AgentGraphDefinition): string {
  return graph.nodes.find((n) => n.type === "start")?.id ?? "";
}

// ─── JSON Import/Export (already exists, but add a typed wrapper) ───

export function exportGraphAsJson(graph: AgentGraphDefinition): string {
  return JSON.stringify(graph, null, 2);
}

export function importGraphFromJson(jsonStr: string): AgentGraphDefinition | null {
  try {
    const data = JSON.parse(jsonStr);
    if (data && data.version === 1 && Array.isArray(data.nodes) && Array.isArray(data.edges)) {
      return data as AgentGraphDefinition;
    }
    return null;
  } catch {
    return null;
  }
}

// ─── Export Dialog Data ───

export interface ExportFormat {
  id: string;
  label: string;
  description: string;
  category: "visual" | "code" | "data";
  icon: string;
  extension: string;
}

export const EXPORT_FORMATS: ExportFormat[] = [
  { id: "png", label: "PNG Image", description: "High-resolution raster image (3x)", category: "visual", icon: "🖼️", extension: ".png" },
  { id: "svg", label: "SVG Vector", description: "Scalable vector graphic", category: "visual", icon: "📐", extension: ".svg" },
  { id: "pdf", label: "PDF Document", description: "Print-ready document", category: "visual", icon: "📄", extension: ".pdf" },
  { id: "mermaid", label: "Mermaid.js", description: "Flowchart diagram code", category: "code", icon: "🧜", extension: ".md" },
  { id: "langgraph-py", label: "LangGraph Python", description: "Python StateGraph code", category: "code", icon: "🐍", extension: ".py" },
  { id: "langgraph-ts", label: "LangGraph TypeScript", description: "TypeScript StateGraph code", category: "code", icon: "📘", extension: ".ts" },
  { id: "json", label: "JSON Schema", description: "Graph definition (import/export)", category: "data", icon: "📋", extension: ".json" },
];

// ─── Helpers ───

function downloadDataUrl(dataUrl: string, filename: string) {
  const link = document.createElement("a");
  link.download = filename;
  link.href = dataUrl;
  link.click();
}
