import { GraphNodeType } from "@/types/graph";
import {
  CircleDot,
  Target,
  Bot,
  GitFork,
  Wrench,
  ShieldCheck,
  Repeat,
  Split,
  Flag,
  Boxes,
  ServerCog,
  Plug,
  Puzzle,
  Globe,
  Shuffle,
  Timer,
  Layers,
  Variable,
  FileOutput,
  StickyNote,
  Frame,
  Clock,
  Radio,
  Rss,
  FileText,
  Send,
  Binary,
  Search,
  FileSpreadsheet,
  FileCheck,
  HardDrive,
  Database,
  BrainCircuit,
  Mic,
  Volume2,
  type LucideIcon,
} from "lucide-react";

export interface CanvasNodeTypeMeta {
  type: GraphNodeType;
  label: string;
  tag: string;
  category?: "triggers" | "agent_core" | "actions_apis" | "data_ops" | "visuals";
  icon: LucideIcon;
  description: string;
  /** Tailwind classes for the node accent (border + text + glow). */
  accent: string;
  badgeClass: string;
  /** Default config injected when a node of this type is dropped. */
  defaults: Partial<Record<string, unknown>>;
}

export const CANVAS_NODE_TYPES: CanvasNodeTypeMeta[] = [
  {
    type: "start",
    label: "START",
    tag: "ENTRY",
    icon: CircleDot,
    description: "Graph entry point — receives the user input.",
    accent: "border-emerald-500/70 text-emerald-600 dark:text-emerald-500",
    badgeClass: "bg-emerald-50 dark:bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/40",
    defaults: {},
  },
  {
    type: "end",
    label: "END",
    tag: "EXIT",
    icon: Flag,
    description: "Terminal node — assembles the final output.",
    accent: "border-rose-500/70 text-rose-600 dark:text-rose-500",
    badgeClass: "bg-rose-50 dark:bg-rose-500/15 text-rose-700 dark:text-rose-400 border-rose-200 dark:border-rose-500/40",
    defaults: {},
  },
  {
    type: "agent",
    label: "AGENT",
    tag: "LLM",
    icon: Bot,
    description: "LLM agent node — runs a prompt over the accumulated context.",
    accent: "border-indigo-500/70 text-indigo-600 dark:text-indigo-400",
    badgeClass: "bg-indigo-50 dark:bg-indigo-500/15 text-indigo-700 dark:text-indigo-400 border-indigo-200 dark:border-indigo-500/40",
    defaults: {
      prompt:
        "You are a specialized agent in a multi-agent workflow. Analyze the provided context thoroughly and produce a detailed, structured response.",
      allowedTools: [],
    },
  },
  {
    type: "supervisor",
    label: "SUPERVISOR",
    tag: "ROUTER·LLM",
    icon: GitFork,
    description: "Orchestrator agent — the LLM picks the next node by edge label.",
    accent: "border-violet-500/70 text-violet-600 dark:text-violet-400",
    badgeClass: "bg-violet-50 dark:bg-violet-500/15 text-violet-700 dark:text-violet-400 border-violet-200 dark:border-violet-500/40",
    defaults: {
      prompt:
        "You are the supervisor of a multi-agent system. Decide which specialist should handle the current task next.",
    },
  },
  {
    type: "tool",
    label: "TOOL",
    tag: "DETERMINISTIC",
    icon: Wrench,
    description: "Deterministic tool invocation (search, calculator, extraction…).",
    accent: "border-cyan-500/70 text-cyan-600 dark:text-cyan-400",
    badgeClass: "bg-cyan-50 dark:bg-cyan-500/15 text-cyan-700 dark:text-cyan-400 border-cyan-200 dark:border-cyan-500/40",
    defaults: {
      toolName: "calculator",
      action: "add",
      inputTemplate: {},
    },
  },
  {
    type: "router",
    label: "ROUTER",
    tag: "CONDITION",
    icon: Split,
    description: "Deterministic or AI branch — picks an outgoing edge by condition.",
    accent: "border-amber-500/70 text-amber-600 dark:text-amber-400",
    badgeClass: "bg-amber-50 dark:bg-amber-500/15 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-500/40",
    defaults: {
      routerMode: "deterministic",
      condition: 'results.classifier.decision == "high"',
    },
  },
  {
    type: "approval",
    label: "APPROVAL",
    tag: "HITL",
    icon: ShieldCheck,
    description: "Human-in-the-loop gate — pauses the run until approved.",
    accent: "border-orange-500/70 text-orange-600 dark:text-orange-400",
    badgeClass: "bg-orange-50 dark:bg-orange-500/15 text-orange-700 dark:text-orange-400 border-orange-200 dark:border-orange-500/40",
    defaults: {
      action: "approve_graph_action",
      approvalReason: "A human review checkpoint in the agent workflow.",
    },
  },
  {
    type: "loop",
    label: "LOOP",
    tag: "COUNTER",
    icon: Repeat,
    description: "Repeats its body edge up to N iterations, then exits.",
    accent: "border-fuchsia-500/70 text-fuchsia-600 dark:text-fuchsia-400",
    badgeClass: "bg-fuchsia-50 dark:bg-fuchsia-500/15 text-fuchsia-700 dark:text-fuchsia-400 border-fuchsia-200 dark:border-fuchsia-500/40",
    defaults: {
      maxIterations: 3,
    },
  },
  {
    type: "parallel",
    label: "PARALLEL",
    tag: "MAP·REDUCE",
    icon: Target,
    description: "Map over an array or fan out branches concurrently.",
    accent: "border-teal-500/70 text-teal-600 dark:text-teal-400",
    badgeClass: "bg-teal-50 dark:bg-teal-500/15 text-teal-700 dark:text-teal-400 border-teal-200 dark:border-teal-500/40",
    defaults: {
      parallelMode: "map",
      mapField: "input.items",
    },
  },
  {
    type: "subgraph",
    label: "SUBGRAPH",
    tag: "MACRO",
    icon: Boxes,
    description: "Nested agent graph — a reusable macro with typed inputs and outputs.",
    accent: "border-slate-500/70 text-slate-600 dark:text-slate-300",
    badgeClass: "bg-slate-100 dark:bg-slate-500/15 text-slate-700 dark:text-slate-300 border-slate-300 dark:border-slate-500/40",
    defaults: {
      inputMapping: {},
      outputMapping: {},
    },
  },
  // ─── MCP & Ecosystem Nodes ───
  {
    type: "mcp_server",
    label: "MCP SERVER",
    tag: "CONNECTOR",
    icon: ServerCog,
    description: "Connect to an MCP server (GitHub, Postgres, Slack, Brave Search, etc.).",
    accent: "border-violet-500/70 text-violet-600 dark:text-violet-400",
    badgeClass: "bg-violet-50 dark:bg-violet-500/15 text-violet-700 dark:text-violet-400 border-violet-200 dark:border-violet-500/40",
    defaults: {
      mcpServerId: "github",
      mcpTransport: "SSE",
    },
  },
  {
    type: "mcp_tool",
    label: "MCP TOOL",
    tag: "REMOTE CALL",
    icon: Plug,
    description: "Call a specific tool from a connected MCP server.",
    accent: "border-fuchsia-500/70 text-fuchsia-600 dark:text-fuchsia-400",
    badgeClass: "bg-fuchsia-50 dark:bg-fuchsia-500/15 text-fuchsia-700 dark:text-fuchsia-400 border-fuchsia-200 dark:border-fuchsia-500/40",
    defaults: {
      mcpToolName: "search_repositories",
      mcpToolServer: "github",
      mcpToolParams: {},
    },
  },
  {
    type: "skill",
    label: "SKILL",
    tag: "MARKETPLACE",
    icon: Puzzle,
    description: "Execute an installed agent skill from the marketplace (19K+ available).",
    accent: "border-sky-500/70 text-sky-600 dark:text-sky-400",
    badgeClass: "bg-sky-50 dark:bg-sky-500/15 text-sky-700 dark:text-sky-400 border-sky-200 dark:border-sky-500/40",
    defaults: {
      skillId: "",
      skillInput: {},
    },
  },
  {
    type: "http",
    label: "HTTP REQUEST",
    tag: "API CALL",
    icon: Globe,
    description: "Make an HTTP request to any REST/GraphQL API endpoint.",
    accent: "border-cyan-500/70 text-cyan-600 dark:text-cyan-400",
    badgeClass: "bg-cyan-50 dark:bg-cyan-500/15 text-cyan-700 dark:text-cyan-400 border-cyan-200 dark:border-cyan-500/40",
    defaults: {
      httpMethod: "GET",
      httpUrl: "https://api.example.com/endpoint",
      httpHeaders: {},
      httpBody: {},
      httpResponseType: "json",
    },
  },
  {
    type: "transform",
    label: "TRANSFORM",
    tag: "DATA OPS",
    icon: Shuffle,
    description: "Transform data: map, filter, merge, flatten, sort, dedupe, pick, omit.",
    accent: "border-emerald-500/70 text-emerald-600 dark:text-emerald-400",
    badgeClass: "bg-emerald-50 dark:bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/40",
    defaults: {
      transformOp: "map",
      transformExpr: "item.name",
    },
  },
  {
    type: "delay",
    label: "DELAY",
    tag: "WAIT",
    icon: Timer,
    description: "Pause execution for a specified duration (ms or template).",
    accent: "border-slate-500/70 text-slate-600 dark:text-slate-400",
    badgeClass: "bg-slate-100 dark:bg-slate-500/15 text-slate-700 dark:text-slate-400 border-slate-300 dark:border-slate-500/40",
    defaults: {
      delayMs: 1000,
    },
  },
  {
    type: "aggregate",
    label: "AGGREGATE",
    tag: "COMBINE",
    icon: Layers,
    description: "Combine results from multiple incoming branches (concat, merge, count, first, all).",
    accent: "border-amber-500/70 text-amber-600 dark:text-amber-400",
    badgeClass: "bg-amber-50 dark:bg-amber-500/15 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-500/40",
    defaults: {
      aggregateMode: "concat",
    },
  },
  {
    type: "variable",
    label: "VARIABLE",
    tag: "STATE",
    icon: Variable,
    description: "Get or set a workflow variable in the execution state.",
    accent: "border-indigo-500/70 text-indigo-600 dark:text-indigo-400",
    badgeClass: "bg-indigo-50 dark:bg-indigo-500/15 text-indigo-700 dark:text-indigo-400 border-indigo-200 dark:border-indigo-500/40",
    defaults: {
      varName: "myVar",
      varOp: "get",
    },
  },
  {
    type: "output",
    label: "OUTPUT",
    tag: "FORMAT",
    icon: FileOutput,
    description: "Format and return the final output with field mappings.",
    accent: "border-teal-500/70 text-teal-600 dark:text-teal-400",
    badgeClass: "bg-teal-50 dark:bg-teal-500/15 text-teal-700 dark:text-teal-400 border-teal-200 dark:border-teal-500/40",
    defaults: {
      outputTemplate: "{{ results }}",
      outputFields: {},
    },
  },
  // ─── Triggers & Event Nodes ───
  {
    type: "schedule_trigger",
    label: "SCHEDULE TRIGGER",
    tag: "CRON·TIMER",
    icon: Clock,
    description: "Scheduled recurrent trigger (cron expression, interval, or timer).",
    accent: "border-blue-500/70 text-blue-600 dark:text-blue-400",
    badgeClass: "bg-blue-50 dark:bg-blue-500/15 text-blue-700 dark:text-blue-400 border-blue-200 dark:border-blue-500/40",
    defaults: {
      cronExpression: "0 9 * * *",
      cronTimezone: "UTC",
      scheduleInterval: "Every day at 9:00 AM UTC",
    },
  },
  {
    type: "webhook_trigger",
    label: "WEBHOOK TRIGGER",
    tag: "INBOUND·API",
    icon: Radio,
    description: "Inbound HTTP webhook listener endpoint for event-driven agent runs.",
    accent: "border-purple-500/70 text-purple-600 dark:text-purple-400",
    badgeClass: "bg-purple-50 dark:bg-purple-500/15 text-purple-700 dark:text-purple-400 border-purple-200 dark:border-purple-500/40",
    defaults: {
      webhookPath: "/api/webhooks/incoming",
      webhookMethod: "POST",
    },
  },
  // ─── Public API, Ingestion & Web Nodes ───
  {
    type: "rss_feed",
    label: "RSS / ATOM FEED",
    tag: "FEED·INGEST",
    icon: Rss,
    description: "Poll and parse any RSS/Atom feed (Substack, Medium, YouTube, News).",
    accent: "border-orange-500/70 text-orange-600 dark:text-orange-400",
    badgeClass: "bg-orange-50 dark:bg-orange-500/15 text-orange-700 dark:text-orange-400 border-orange-200 dark:border-orange-500/40",
    defaults: {
      rssUrl: "https://news.ycombinator.com/rss",
      rssMaxItems: 10,
    },
  },
  {
    type: "web_reader",
    label: "JINA WEB READER",
    tag: "JINA·MARKDOWN",
    icon: FileText,
    description: "Convert any live website URL into clean LLM-ready markdown (r.jina.ai).",
    accent: "border-emerald-500/70 text-emerald-600 dark:text-emerald-400",
    badgeClass: "bg-emerald-50 dark:bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/40",
    defaults: {
      readerUrl: "https://github.com/trending",
      readerFormat: "markdown",
    },
  },
  // ─── Actions & Integrations ───
  {
    type: "notification_dispatcher",
    label: "WEBHOOK DISPATCHER",
    tag: "DISCORD·SLACK",
    icon: Send,
    description: "One-click notification dispatch to Discord, Slack, Telegram, or Webhooks.",
    accent: "border-sky-500/70 text-sky-600 dark:text-sky-400",
    badgeClass: "bg-sky-50 dark:bg-sky-500/15 text-sky-700 dark:text-sky-400 border-sky-200 dark:border-sky-500/40",
    defaults: {
      dispatchDestination: "discord",
      dispatchWebhookUrl: "",
      dispatchMessage: "**Workflow Complete:**\n{{ results }}",
    },
  },
  // ─── Data Formatter / Mapping ───
  {
    type: "data_mapper",
    label: "DATA MAPPER",
    tag: "JSONPATH·MAP",
    icon: Binary,
    description: "Visual data mapper & JSONPath extractor to shape payloads before LLM agents.",
    accent: "border-pink-500/70 text-pink-600 dark:text-pink-400",
    badgeClass: "bg-pink-50 dark:bg-pink-500/15 text-pink-700 dark:text-pink-400 border-pink-200 dark:border-pink-500/40",
    defaults: {
      mapperSchema: {
        title: "item.title",
        url: "item.url",
        score: "item.score",
      },
    },
  },
  // ─── Open-Source Microservices & Local Tools ───
  {
    type: "searxng_search",
    label: "SEARXNG SEARCH",
    tag: "OPEN SEARCH",
    icon: Search,
    description: "Query free metasearch (Google/Bing/DDG/Reddit) via any public or self-hosted SearXNG instance.",
    accent: "border-sky-500/70 text-sky-600 dark:text-sky-400",
    badgeClass: "bg-sky-50 dark:bg-sky-500/15 text-sky-700 dark:text-sky-400 border-sky-200 dark:border-sky-500/40",
    defaults: {
      searxngHost: "https://searx.be",
      searxngQuery: "autonomous AI agents",
      searxngCategories: ["general"],
      searxngLimit: 5,
    },
  },
  {
    type: "crawl4ai_scrape",
    label: "CRAWL4AI SCRAPER",
    tag: "AI CRAWLER",
    icon: FileSpreadsheet,
    description: "Crawl and extract LLM-tailored structured markdown with boilerplate stripping.",
    accent: "border-emerald-500/70 text-emerald-600 dark:text-emerald-400",
    badgeClass: "bg-emerald-50 dark:bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/40",
    defaults: {
      crawl4aiUrl: "https://github.com/unclecode/crawl4ai",
      crawl4aiWordCountThreshold: 10,
      crawl4aiHost: "http://localhost:11235",
    },
  },
  {
    type: "docling_pdf_parser",
    label: "DOCLING PARSER",
    tag: "PDF & DOCX",
    icon: FileCheck,
    description: "Parse complex PDFs, research papers, and DOCX into structured tables and markdown (by IBM).",
    accent: "border-cyan-500/70 text-cyan-600 dark:text-cyan-400",
    badgeClass: "bg-cyan-50 dark:bg-cyan-500/15 text-cyan-700 dark:text-cyan-400 border-cyan-200 dark:border-cyan-500/40",
    defaults: {
      doclingDocumentUrl: "https://arxiv.org/pdf/1706.03762.pdf",
      doclingOutputFormat: "markdown",
      doclingOcr: true,
      doclingHost: "http://localhost:5001",
    },
  },
  {
    type: "gotenberg_pdf_exporter",
    label: "GOTENBERG PDF",
    tag: "PDF EXPORT",
    icon: FileOutput,
    description: "Convert HTML/Markdown into publication-ready PDF documents & reports.",
    accent: "border-rose-500/70 text-rose-600 dark:text-rose-400",
    badgeClass: "bg-rose-50 dark:bg-rose-500/15 text-rose-700 dark:text-rose-400 border-rose-200 dark:border-rose-500/40",
    defaults: {
      gotenbergHost: "http://localhost:3000",
      gotenbergHtmlContent: "# Executive Report\n\n{{ results }}",
      gotenbergPaperSize: "A4",
      gotenbergLandscape: false,
    },
  },
  {
    type: "nocodb_record",
    label: "NOCODB RECORD",
    tag: "AIRTABLE·DB",
    icon: Database,
    description: "Read, create, or update records in open-source NocoDB tables.",
    accent: "border-amber-500/70 text-amber-600 dark:text-amber-400",
    badgeClass: "bg-amber-50 dark:bg-amber-500/15 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-500/40",
    defaults: {
      nocodbHost: "http://localhost:8080",
      nocodbOperation: "create",
      nocodbTableId: "tbl_leads",
      nocodbData: {},
    },
  },
  {
    type: "pocketbase_store",
    label: "POCKETBASE STORE",
    tag: "KV·STATE",
    icon: HardDrive,
    description: "Persist graph state, session logs, and key-value records in lightweight PocketBase.",
    accent: "border-indigo-500/70 text-indigo-600 dark:text-indigo-400",
    badgeClass: "bg-indigo-50 dark:bg-indigo-500/15 text-indigo-700 dark:text-indigo-400 border-indigo-200 dark:border-indigo-500/40",
    defaults: {
      pocketbaseHost: "http://127.0.0.1:8090",
      pocketbaseCollection: "agent_state",
      pocketbaseAction: "create",
      pocketbaseData: {},
    },
  },
  {
    type: "qdrant_vector_memory",
    label: "QDRANT MEMORY",
    tag: "VECTOR RAG",
    icon: BrainCircuit,
    description: "Perform semantic search & recall from open-source Qdrant vector collections.",
    accent: "border-purple-500/70 text-purple-600 dark:text-purple-400",
    badgeClass: "bg-purple-50 dark:bg-purple-500/15 text-purple-700 dark:text-purple-400 border-purple-200 dark:border-purple-500/40",
    defaults: {
      qdrantHost: "http://localhost:6333",
      qdrantCollection: "knowledge_base",
      qdrantAction: "search",
      qdrantTopK: 3,
      qdrantQuery: "{{ input.query }}",
    },
  },
  {
    type: "audio_transcriber",
    label: "AUDIO TRANSCRIBER",
    tag: "WHISPER·STT",
    icon: Mic,
    description: "Transcribe audio memos, recordings, and podcasts into text via Faster-Whisper.",
    accent: "border-violet-500/70 text-violet-600 dark:text-violet-400",
    badgeClass: "bg-violet-50 dark:bg-violet-500/15 text-violet-700 dark:text-violet-400 border-violet-200 dark:border-violet-500/40",
    defaults: {
      audioSourceUrl: "{{ input.audioUrl }}",
      audioLanguage: "auto",
      audioTranscriberHost: "http://localhost:8000",
    },
  },
  {
    type: "piper_tts",
    label: "PIPER TTS",
    tag: "VOICE·TTS",
    icon: Volume2,
    description: "Synthesize agent responses into realistic local speech audio via Piper.",
    accent: "border-teal-500/70 text-teal-600 dark:text-teal-400",
    badgeClass: "bg-teal-50 dark:bg-teal-500/15 text-teal-700 dark:text-teal-400 border-teal-200 dark:border-teal-500/40",
    defaults: {
      piperText: "{{ results }}",
      piperVoice: "en_US-lessac-medium",
      piperHost: "http://localhost:5000",
    },
  },
  // ─── Visual & Documentation Nodes ───
  {
    type: "sticky_note",
    label: "STICKY NOTE",
    tag: "DOCS",
    icon: StickyNote,
    description: "Markdown sticky note for inline architecture documentation and team comments.",
    accent: "border-yellow-400/70 text-yellow-600 dark:text-yellow-400",
    badgeClass: "bg-yellow-50 dark:bg-yellow-500/15 text-yellow-700 dark:text-yellow-400 border-yellow-200 dark:border-yellow-500/40",
    defaults: {
      noteContent: "# Notes\n\nAdd documentation here...",
      noteColor: "yellow",
    },
  },
  {
    type: "frame",
    label: "FRAME",
    tag: "GROUP",
    icon: Frame,
    description: "Visual container to group nodes (e.g. 'Research Phase', 'Validation Stage').",
    accent: "border-indigo-400/70 text-indigo-600 dark:text-indigo-400",
    badgeClass: "bg-indigo-50 dark:bg-indigo-500/15 text-indigo-700 dark:text-indigo-400 border-indigo-200 dark:border-indigo-500/40",
    defaults: {
      frameTitle: "Phase",
      frameOpacity: 0.08,
      containedNodeIds: [],
    },
  },
];

export const CANVAS_NODE_TYPE_MAP: Record<GraphNodeType, CanvasNodeTypeMeta> = Object.fromEntries(
  CANVAS_NODE_TYPES.map((meta) => [meta.type, meta])
) as Record<GraphNodeType, CanvasNodeTypeMeta>;
